/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PButton: typeof import('primevue/button')['default']
    PColumn: typeof import('primevue/column')['default']
    PConfirmDialog: typeof import('primevue/confirmdialog')['default']
    PDataTable: typeof import('primevue/datatable')['default']
    PDialog: typeof import('primevue/dialog')['default']
    PInputNumber: typeof import('primevue/inputnumber')['default']
    PMultiSelect: typeof import('primevue/multiselect')['default']
    PToggleButton: typeof import('primevue/togglebutton')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
