name: Deploy to Droplet

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 9
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build and Generate
        run: |
          pnpm build
          pnpm generate

      - name: Archive production artifacts
        run: tar -zcvf dist.tar.gz ./dist

      - name: Deploy to Droplet
        uses: appleboy/scp-action@master
        with:
          host: your_droplet_ip
          username: deployer
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: 22
          source: "dist.tar.gz"
          target: "/var/www/rounding.teschmacher.dev/html"

      - name: Extract artifacts on server
        uses: appleboy/ssh-action@master
        with:
          host: your_droplet_ip
          username: deployer
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: 22
          script: |
            cd /var/www/rounding.teschmacher.dev/html
            tar -zxvf dist.tar.gz --strip 1
            rm dist.tar.gz
